# -*- coding: utf-8 -*-

# Name: iftd_monitor_view
# Description: IFTD实时监控软件
# Author: Wang Xueliang
# Date: 2019/8/1

from PyQt5.QtCore import Qt, QSize, QCoreApplication
from PyQt5.QtGui import QFont, QIcon
from PyQt5.QtWidgets import (QMainWindow, QWidget, QVBoxLayout, QHBoxLayout, QGroupBox,
                             QApplication, QGridLayout, QLabel, QFrame,
                             QToolBar, QStackedWidget)

from pyqtgraph import GraphicsView


class IFTDMonitorView(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)

        # UI界面
        font = QFont()
        font.setFamily('微软雅黑')
        self.setFont(font)
        self.setGeometry(50, 50, 1050, 600)
        self.setWindowState(Qt.WindowMaximized)
        self.setMinimumSize(QSize(1050, 600))

        # 创建工具栏
        self.toolBar = QToolBar(self)
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.addToolBar(Qt.TopToolBarArea, self.toolBar)
        # 创建信息栏
        self.status_bar = self.statusBar()
        
        self.centralwidget = QWidget(self, flags=Qt.Widget)
        self.verticalLayout_4 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setSpacing(4)
        
        self.stack_window = QStackedWidget(self.centralwidget)
        self.left_eng_win = QWidget(self.stack_window, flags=Qt.Widget)
        self.verticalLayout_7 = QVBoxLayout(self.left_eng_win)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setSpacing(4)
        self.aux_graphics_left_eng = GraphicsView(self.left_eng_win)
        self.verticalLayout_7.addWidget(self.aux_graphics_left_eng)
        self.horizontalLayout_2 = QHBoxLayout()
        self.verticalLayout_5 = QVBoxLayout()
        self.main_graphics_left_eng = GraphicsView(self.left_eng_win)
        self.verticalLayout_5.addWidget(self.main_graphics_left_eng)
        self.groupBox_4 = QGroupBox(self.left_eng_win)
        self.gridLayout_4 = QGridLayout(self.groupBox_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(4)
        self.tf_dnst_l_l = QLabel(self.groupBox_4)
        self.tf_dnst_l_l.setMinimumSize(QSize(0, 24))
        self.tf_dnst_l_l.setMaximumSize(QSize(16777215, 24))
        self.tf_dnst_l_l.setFrameShape(QFrame.Box)
        self.tf_dnst_l_l.setText('')
        self.gridLayout_4.addWidget(self.tf_dnst_l_l, 1, 6, 1, 1)
        self.label_qf_upst_l = QLabel(self.groupBox_4)
        self.label_qf_upst_l.setMinimumSize(QSize(0, 24))
        self.label_qf_upst_l.setMaximumSize(QSize(16777215, 24))
        self.label_qf_upst_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_qf_upst_l, 0, 1, 1, 1)
        self.label_tf_upst_l = QLabel(self.groupBox_4)
        self.label_tf_upst_l.setMinimumSize(QSize(0, 24))
        self.label_tf_upst_l.setMaximumSize(QSize(16777215, 24))
        self.label_tf_upst_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_tf_upst_l, 0, 5, 1, 1)
        self.qf_dnst_l_l = QLabel(self.groupBox_4)
        self.qf_dnst_l_l.setMinimumSize(QSize(0, 24))
        self.qf_dnst_l_l.setMaximumSize(QSize(16777215, 24))
        self.qf_dnst_l_l.setFrameShape(QFrame.Box)
        self.qf_dnst_l_l.setText('')
        self.gridLayout_4.addWidget(self.qf_dnst_l_l, 1, 2, 1, 1)
        self.label_pf_upst_l = QLabel(self.groupBox_4)
        self.label_pf_upst_l.setMinimumSize(QSize(0, 24))
        self.label_pf_upst_l.setMaximumSize(QSize(16777215, 24))
        self.label_pf_upst_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_pf_upst_l, 0, 3, 1, 1)
        self.label_pf_dnst_l = QLabel(self.groupBox_4)
        self.label_pf_dnst_l.setMinimumSize(QSize(0, 24))
        self.label_pf_dnst_l.setMaximumSize(QSize(16777215, 24))
        self.label_pf_dnst_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_pf_dnst_l, 0, 4, 1, 1)
        self.qf_upst_l_l = QLabel(self.groupBox_4)
        self.qf_upst_l_l.setMinimumSize(QSize(0, 24))
        self.qf_upst_l_l.setMaximumSize(QSize(16777215, 24))
        self.qf_upst_l_l.setFrameShape(QFrame.Box)
        self.qf_upst_l_l.setText('')
        self.gridLayout_4.addWidget(self.qf_upst_l_l, 1, 1, 1, 1)
        self.label_l_l = QLabel(self.groupBox_4)
        self.label_l_l.setMinimumSize(QSize(24, 24))
        self.label_l_l.setMaximumSize(QSize(24, 24))
        self.label_l_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_l_l, 1, 0, 1, 1)
        self.pf_upst_l_l = QLabel(self.groupBox_4)
        self.pf_upst_l_l.setMinimumSize(QSize(0, 24))
        self.pf_upst_l_l.setMaximumSize(QSize(16777215, 24))
        self.pf_upst_l_l.setFrameShape(QFrame.Box)
        self.pf_upst_l_l.setText('')
        self.gridLayout_4.addWidget(self.pf_upst_l_l, 1, 3, 1, 1)
        self.label_qf_dnst_l = QLabel(self.groupBox_4)
        self.label_qf_dnst_l.setMinimumSize(QSize(0, 24))
        self.label_qf_dnst_l.setMaximumSize(QSize(16777215, 24))
        self.label_qf_dnst_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_qf_dnst_l, 0, 2, 1, 1)
        self.label_tf_dnst_l = QLabel(self.groupBox_4)
        self.label_tf_dnst_l.setMinimumSize(QSize(0, 24))
        self.label_tf_dnst_l.setMaximumSize(QSize(16777215, 24))
        self.label_tf_dnst_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_tf_dnst_l, 0, 6, 1, 1)
        self.pf_dnst_l_l = QLabel(self.groupBox_4)
        self.pf_dnst_l_l.setMinimumSize(QSize(0, 24))
        self.pf_dnst_l_l.setMaximumSize(QSize(16777215, 24))
        self.pf_dnst_l_l.setFrameShape(QFrame.Box)
        self.pf_dnst_l_l.setText('')
        self.gridLayout_4.addWidget(self.pf_dnst_l_l, 1, 4, 1, 1)
        self.label_l_spacer_2 = QLabel(self.groupBox_4)
        self.label_l_spacer_2.setMinimumSize(QSize(24, 24))
        self.label_l_spacer_2.setMaximumSize(QSize(24, 24))
        self.label_l_spacer_2.setText('')
        self.gridLayout_4.addWidget(self.label_l_spacer_2, 0, 0, 1, 1)
        self.tf_upst_l_l = QLabel(self.groupBox_4)
        self.tf_upst_l_l.setMinimumSize(QSize(0, 24))
        self.tf_upst_l_l.setMaximumSize(QSize(16777215, 24))
        self.tf_upst_l_l.setFrameShape(QFrame.Box)
        self.tf_upst_l_l.setText('')
        self.gridLayout_4.addWidget(self.tf_upst_l_l, 1, 5, 1, 1)
        self.pf_upst_r_l = QLabel(self.groupBox_4)
        self.pf_upst_r_l.setMinimumSize(QSize(0, 24))
        self.pf_upst_r_l.setMaximumSize(QSize(16777215, 24))
        self.pf_upst_r_l.setFrameShape(QFrame.Box)
        self.pf_upst_r_l.setText('')
        self.gridLayout_4.addWidget(self.pf_upst_r_l, 2, 3, 1, 1)
        self.qf_dnst_r_l = QLabel(self.groupBox_4)
        self.qf_dnst_r_l.setMinimumSize(QSize(0, 24))
        self.qf_dnst_r_l.setMaximumSize(QSize(16777215, 24))
        self.qf_dnst_r_l.setFrameShape(QFrame.Box)
        self.qf_dnst_r_l.setText('')
        self.gridLayout_4.addWidget(self.qf_dnst_r_l, 2, 2, 1, 1)
        self.tf_upst_r_l = QLabel(self.groupBox_4)
        self.tf_upst_r_l.setMinimumSize(QSize(0, 24))
        self.tf_upst_r_l.setMaximumSize(QSize(16777215, 24))
        self.tf_upst_r_l.setFrameShape(QFrame.Box)
        self.tf_upst_r_l.setText('')
        self.gridLayout_4.addWidget(self.tf_upst_r_l, 2, 5, 1, 1)
        self.pf_dnst_r_l = QLabel(self.groupBox_4)
        self.pf_dnst_r_l.setMinimumSize(QSize(0, 24))
        self.pf_dnst_r_l.setMaximumSize(QSize(16777215, 24))
        self.pf_dnst_r_l.setFrameShape(QFrame.Box)
        self.pf_dnst_r_l.setText('')
        self.gridLayout_4.addWidget(self.pf_dnst_r_l, 2, 4, 1, 1)
        self.label_r_l = QLabel(self.groupBox_4)
        self.label_r_l.setMinimumSize(QSize(24, 24))
        self.label_r_l.setMaximumSize(QSize(24, 24))
        self.label_r_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_4.addWidget(self.label_r_l, 2, 0, 1, 1)
        self.qf_upst_r_l = QLabel(self.groupBox_4)
        self.qf_upst_r_l.setMinimumSize(QSize(0, 24))
        self.qf_upst_r_l.setMaximumSize(QSize(16777215, 24))
        self.qf_upst_r_l.setFrameShape(QFrame.Box)
        self.qf_upst_r_l.setText('')
        self.gridLayout_4.addWidget(self.qf_upst_r_l, 2, 1, 1, 1)
        self.tf_dnst_r_l = QLabel(self.groupBox_4)
        self.tf_dnst_r_l.setMinimumSize(QSize(0, 24))
        self.tf_dnst_r_l.setMaximumSize(QSize(16777215, 24))
        self.tf_dnst_r_l.setFrameShape(QFrame.Box)
        self.tf_dnst_r_l.setText('')
        self.gridLayout_4.addWidget(self.tf_dnst_r_l, 2, 6, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QVBoxLayout()
        self.groupBox_5 = QGroupBox(self.left_eng_win)
        self.gridLayout_5 = QGridLayout(self.groupBox_5)
        self.gridLayout_5.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_5.setSpacing(4)
        self.label_a_l = QLabel(self.groupBox_5)
        self.label_a_l.setMinimumSize(QSize(0, 24))
        self.label_a_l.setMaximumSize(QSize(16777215, 24))
        self.label_a_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_a_l, 0, 1, 1, 1)
        self.label_b_l = QLabel(self.groupBox_5)
        self.label_b_l.setMinimumSize(QSize(0, 24))
        self.label_b_l.setMaximumSize(QSize(16777215, 24))
        self.label_b_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_b_l, 0, 2, 1, 1)
        self.label_c_l = QLabel(self.groupBox_5)
        self.label_c_l.setMinimumSize(QSize(0, 24))
        self.label_c_l.setMaximumSize(QSize(16777215, 24))
        self.label_c_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_c_l, 0, 3, 1, 1)
        self.label_d_l = QLabel(self.groupBox_5)
        self.label_d_l.setMinimumSize(QSize(0, 24))
        self.label_d_l.setMaximumSize(QSize(16777215, 24))
        self.label_d_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_d_l, 0, 4, 1, 1)
        self.label_e_l = QLabel(self.groupBox_5)
        self.label_e_l.setMinimumSize(QSize(0, 24))
        self.label_e_l.setMaximumSize(QSize(16777215, 24))
        self.label_e_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_e_l, 0, 5, 1, 1)
        self.label_f_l = QLabel(self.groupBox_5)
        self.label_f_l.setMinimumSize(QSize(0, 24))
        self.label_f_l.setMaximumSize(QSize(16777215, 24))
        self.label_f_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_f_l, 0, 6, 1, 1)
        self.label_pt_25_l = QLabel(self.groupBox_5)
        self.label_pt_25_l.setMinimumSize(QSize(0, 24))
        self.label_pt_25_l.setMaximumSize(QSize(16777215, 24))
        self.label_pt_25_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_pt_25_l, 1, 0, 1, 1)
        self.pt_25_a_l = QLabel(self.groupBox_5)
        self.pt_25_a_l.setMinimumSize(QSize(0, 24))
        self.pt_25_a_l.setMaximumSize(QSize(16777215, 24))
        self.pt_25_a_l.setFrameShape(QFrame.Box)
        self.pt_25_a_l.setText('')
        self.gridLayout_5.addWidget(self.pt_25_a_l, 1, 1, 1, 1)
        self.pt_25_b_l = QLabel(self.groupBox_5)
        self.pt_25_b_l.setMinimumSize(QSize(0, 24))
        self.pt_25_b_l.setMaximumSize(QSize(16777215, 24))
        self.pt_25_b_l.setFrameShape(QFrame.Box)
        self.pt_25_b_l.setText('')
        self.gridLayout_5.addWidget(self.pt_25_b_l, 1, 2, 1, 1)
        self.pt_25_c_l = QLabel(self.groupBox_5)
        self.pt_25_c_l.setMinimumSize(QSize(0, 24))
        self.pt_25_c_l.setMaximumSize(QSize(16777215, 24))
        self.pt_25_c_l.setFrameShape(QFrame.Box)
        self.pt_25_c_l.setText('')
        self.gridLayout_5.addWidget(self.pt_25_c_l, 1, 3, 1, 1)
        self.pt_25_d_l = QLabel(self.groupBox_5)
        self.pt_25_d_l.setMinimumSize(QSize(0, 24))
        self.pt_25_d_l.setMaximumSize(QSize(16777215, 24))
        self.pt_25_d_l.setFrameShape(QFrame.Box)
        self.pt_25_d_l.setText('')
        self.gridLayout_5.addWidget(self.pt_25_d_l, 1, 4, 1, 1)
        self.pt_25_e_l = QLabel(self.groupBox_5)
        self.pt_25_e_l.setMinimumSize(QSize(0, 24))
        self.pt_25_e_l.setMaximumSize(QSize(16777215, 24))
        self.pt_25_e_l.setFrameShape(QFrame.Box)
        self.pt_25_e_l.setText('')
        self.gridLayout_5.addWidget(self.pt_25_e_l, 1, 5, 1, 1)
        self.pt_25_f_l = QLabel(self.groupBox_5)
        self.pt_25_f_l.setMinimumSize(QSize(0, 24))
        self.pt_25_f_l.setMaximumSize(QSize(16777215, 24))
        self.pt_25_f_l.setFrameShape(QFrame.Box)
        self.pt_25_f_l.setText('')
        self.gridLayout_5.addWidget(self.pt_25_f_l, 1, 6, 1, 1)
        self.label_pt_31_l = QLabel(self.groupBox_5)
        self.label_pt_31_l.setMinimumSize(QSize(0, 24))
        self.label_pt_31_l.setMaximumSize(QSize(16777215, 24))
        self.label_pt_31_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_pt_31_l, 2, 0, 1, 1)
        self.pt_31_a_l = QLabel(self.groupBox_5)
        self.pt_31_a_l.setMinimumSize(QSize(0, 24))
        self.pt_31_a_l.setMaximumSize(QSize(16777215, 24))
        self.pt_31_a_l.setFrameShape(QFrame.Box)
        self.pt_31_a_l.setText('')
        self.gridLayout_5.addWidget(self.pt_31_a_l, 2, 1, 1, 1)
        self.pt_31_b_l = QLabel(self.groupBox_5)
        self.pt_31_b_l.setMinimumSize(QSize(0, 24))
        self.pt_31_b_l.setMaximumSize(QSize(16777215, 24))
        self.pt_31_b_l.setFrameShape(QFrame.Box)
        self.pt_31_b_l.setText('')
        self.gridLayout_5.addWidget(self.pt_31_b_l, 2, 2, 1, 1)
        self.pt_31_c_l = QLabel(self.groupBox_5)
        self.pt_31_c_l.setMinimumSize(QSize(0, 24))
        self.pt_31_c_l.setMaximumSize(QSize(16777215, 24))
        self.pt_31_c_l.setFrameShape(QFrame.Box)
        self.pt_31_c_l.setText('')
        self.gridLayout_5.addWidget(self.pt_31_c_l, 2, 3, 1, 1)
        self.pt_31_d_l = QLabel(self.groupBox_5)
        self.pt_31_d_l.setMinimumSize(QSize(0, 24))
        self.pt_31_d_l.setMaximumSize(QSize(16777215, 24))
        self.pt_31_d_l.setFrameShape(QFrame.Box)
        self.pt_31_d_l.setText('')
        self.gridLayout_5.addWidget(self.pt_31_d_l, 2, 4, 1, 1)
        self.pt_31_e_l = QLabel(self.groupBox_5)
        self.pt_31_e_l.setMinimumSize(QSize(0, 24))
        self.pt_31_e_l.setMaximumSize(QSize(16777215, 24))
        self.pt_31_e_l.setFrameShape(QFrame.Box)
        self.pt_31_e_l.setText('')
        self.gridLayout_5.addWidget(self.pt_31_e_l, 2, 5, 1, 1)
        self.label_tt_25_l = QLabel(self.groupBox_5)
        self.label_tt_25_l.setMinimumSize(QSize(0, 24))
        self.label_tt_25_l.setMaximumSize(QSize(16777215, 24))
        self.label_tt_25_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_tt_25_l, 3, 0, 1, 1)
        self.tt_25_a_l = QLabel(self.groupBox_5)
        self.tt_25_a_l.setMinimumSize(QSize(0, 24))
        self.tt_25_a_l.setMaximumSize(QSize(16777215, 24))
        self.tt_25_a_l.setFrameShape(QFrame.Box)
        self.tt_25_a_l.setText('')
        self.gridLayout_5.addWidget(self.tt_25_a_l, 3, 1, 1, 1)
        self.tt_25_b_l = QLabel(self.groupBox_5)
        self.tt_25_b_l.setMinimumSize(QSize(0, 24))
        self.tt_25_b_l.setMaximumSize(QSize(16777215, 24))
        self.tt_25_b_l.setFrameShape(QFrame.Box)
        self.tt_25_b_l.setText('')
        self.gridLayout_5.addWidget(self.tt_25_b_l, 3, 2, 1, 1)
        self.tt_25_c_l = QLabel(self.groupBox_5)
        self.tt_25_c_l.setMinimumSize(QSize(0, 24))
        self.tt_25_c_l.setMaximumSize(QSize(16777215, 24))
        self.tt_25_c_l.setFrameShape(QFrame.Box)
        self.tt_25_c_l.setText('')
        self.gridLayout_5.addWidget(self.tt_25_c_l, 3, 3, 1, 1)
        self.tt_25_d_l = QLabel(self.groupBox_5)
        self.tt_25_d_l.setMinimumSize(QSize(0, 24))
        self.tt_25_d_l.setMaximumSize(QSize(16777215, 24))
        self.tt_25_d_l.setFrameShape(QFrame.Box)
        self.tt_25_d_l.setText('')
        self.gridLayout_5.addWidget(self.tt_25_d_l, 3, 4, 1, 1)
        self.tt_25_e_l = QLabel(self.groupBox_5)
        self.tt_25_e_l.setMinimumSize(QSize(0, 24))
        self.tt_25_e_l.setMaximumSize(QSize(16777215, 24))
        self.tt_25_e_l.setFrameShape(QFrame.Box)
        self.tt_25_e_l.setText('')
        self.gridLayout_5.addWidget(self.tt_25_e_l, 3, 5, 1, 1)
        self.tt_25_f_l = QLabel(self.groupBox_5)
        self.tt_25_f_l.setMinimumSize(QSize(0, 24))
        self.tt_25_f_l.setMaximumSize(QSize(16777215, 24))
        self.tt_25_f_l.setFrameShape(QFrame.Box)
        self.tt_25_f_l.setText('')
        self.gridLayout_5.addWidget(self.tt_25_f_l, 3, 6, 1, 1)
        self.label_tt_31_l = QLabel(self.groupBox_5)
        self.label_tt_31_l.setMinimumSize(QSize(0, 24))
        self.label_tt_31_l.setMaximumSize(QSize(16777215, 24))
        self.label_tt_31_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_tt_31_l, 4, 0, 1, 1)
        self.tt_31_a_l = QLabel(self.groupBox_5)
        self.tt_31_a_l.setMinimumSize(QSize(0, 24))
        self.tt_31_a_l.setMaximumSize(QSize(16777215, 24))
        self.tt_31_a_l.setFrameShape(QFrame.Box)
        self.tt_31_a_l.setText('')
        self.gridLayout_5.addWidget(self.tt_31_a_l, 4, 1, 1, 1)
        self.tt_31_b_l = QLabel(self.groupBox_5)
        self.tt_31_b_l.setMinimumSize(QSize(0, 24))
        self.tt_31_b_l.setMaximumSize(QSize(16777215, 24))
        self.tt_31_b_l.setFrameShape(QFrame.Box)
        self.tt_31_b_l.setText('')
        self.gridLayout_5.addWidget(self.tt_31_b_l, 4, 2, 1, 1)
        self.tt_31_c_l = QLabel(self.groupBox_5)
        self.tt_31_c_l.setMinimumSize(QSize(0, 24))
        self.tt_31_c_l.setMaximumSize(QSize(16777215, 24))
        self.tt_31_c_l.setFrameShape(QFrame.Box)
        self.tt_31_c_l.setText('')
        self.gridLayout_5.addWidget(self.tt_31_c_l, 4, 3, 1, 1)
        self.tt_31_d_l = QLabel(self.groupBox_5)
        self.tt_31_d_l.setMinimumSize(QSize(0, 24))
        self.tt_31_d_l.setMaximumSize(QSize(16777215, 24))
        self.tt_31_d_l.setFrameShape(QFrame.Box)
        self.tt_31_d_l.setText('')
        self.gridLayout_5.addWidget(self.tt_31_d_l, 4, 4, 1, 1)
        self.tt_31_e_l = QLabel(self.groupBox_5)
        self.tt_31_e_l.setMinimumSize(QSize(0, 24))
        self.tt_31_e_l.setMaximumSize(QSize(16777215, 24))
        self.tt_31_e_l.setFrameShape(QFrame.Box)
        self.tt_31_e_l.setText('')
        self.gridLayout_5.addWidget(self.tt_31_e_l, 4, 5, 1, 1)
        self.label_pt_79_l = QLabel(self.groupBox_5)
        self.label_pt_79_l.setMinimumSize(QSize(0, 24))
        self.label_pt_79_l.setMaximumSize(QSize(16777215, 24))
        self.label_pt_79_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_pt_79_l, 5, 0, 1, 1)
        self.pt_79_a_l = QLabel(self.groupBox_5)
        self.pt_79_a_l.setMinimumSize(QSize(0, 24))
        self.pt_79_a_l.setMaximumSize(QSize(16777215, 24))
        self.pt_79_a_l.setFrameShape(QFrame.Box)
        self.pt_79_a_l.setText('')
        self.gridLayout_5.addWidget(self.pt_79_a_l, 5, 1, 1, 1)
        self.pt_79_b_l = QLabel(self.groupBox_5)
        self.pt_79_b_l.setMinimumSize(QSize(0, 24))
        self.pt_79_b_l.setMaximumSize(QSize(16777215, 24))
        self.pt_79_b_l.setFrameShape(QFrame.Box)
        self.pt_79_b_l.setText('')
        self.gridLayout_5.addWidget(self.pt_79_b_l, 5, 2, 1, 1)
        self.pt_79_c_l = QLabel(self.groupBox_5)
        self.pt_79_c_l.setMinimumSize(QSize(0, 24))
        self.pt_79_c_l.setMaximumSize(QSize(16777215, 24))
        self.pt_79_c_l.setFrameShape(QFrame.Box)
        self.pt_79_c_l.setText('')
        self.gridLayout_5.addWidget(self.pt_79_c_l, 5, 3, 1, 1)
        self.pt_79_d_l = QLabel(self.groupBox_5)
        self.pt_79_d_l.setMinimumSize(QSize(0, 24))
        self.pt_79_d_l.setMaximumSize(QSize(16777215, 24))
        self.pt_79_d_l.setFrameShape(QFrame.Box)
        self.pt_79_d_l.setText('')
        self.gridLayout_5.addWidget(self.pt_79_d_l, 5, 4, 1, 1)
        self.label_tt_79_l = QLabel(self.groupBox_5)
        self.label_tt_79_l.setMinimumSize(QSize(0, 24))
        self.label_tt_79_l.setMaximumSize(QSize(16777215, 24))
        self.label_tt_79_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_tt_79_l, 6, 0, 1, 1)
        self.tt_79_a_l = QLabel(self.groupBox_5)
        self.tt_79_a_l.setMinimumSize(QSize(0, 24))
        self.tt_79_a_l.setMaximumSize(QSize(16777215, 24))
        self.tt_79_a_l.setFrameShape(QFrame.Box)
        self.tt_79_a_l.setText('')
        self.gridLayout_5.addWidget(self.tt_79_a_l, 6, 1, 1, 1)
        self.tt_79_b_l = QLabel(self.groupBox_5)
        self.tt_79_b_l.setMinimumSize(QSize(0, 24))
        self.tt_79_b_l.setMaximumSize(QSize(16777215, 24))
        self.tt_79_b_l.setFrameShape(QFrame.Box)
        self.tt_79_b_l.setText('')
        self.gridLayout_5.addWidget(self.tt_79_b_l, 6, 2, 1, 1)
        self.tt_79_c_l = QLabel(self.groupBox_5)
        self.tt_79_c_l.setMinimumSize(QSize(0, 24))
        self.tt_79_c_l.setMaximumSize(QSize(16777215, 24))
        self.tt_79_c_l.setFrameShape(QFrame.Box)
        self.tt_79_c_l.setText('')
        self.gridLayout_5.addWidget(self.tt_79_c_l, 6, 3, 1, 1)
        self.tt_79_d_l = QLabel(self.groupBox_5)
        self.tt_79_d_l.setMinimumSize(QSize(0, 24))
        self.tt_79_d_l.setMaximumSize(QSize(16777215, 24))
        self.tt_79_d_l.setFrameShape(QFrame.Box)
        self.tt_79_d_l.setText('')
        self.gridLayout_5.addWidget(self.tt_79_d_l, 6, 4, 1, 1)
        self.label_ps_79_l = QLabel(self.groupBox_5)
        self.label_ps_79_l.setMinimumSize(QSize(0, 24))
        self.label_ps_79_l.setMaximumSize(QSize(16777215, 24))
        self.label_ps_79_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_ps_79_l, 7, 0, 1, 1)
        self.ps_79_a_l = QLabel(self.groupBox_5)
        self.ps_79_a_l.setMinimumSize(QSize(0, 24))
        self.ps_79_a_l.setMaximumSize(QSize(16777215, 24))
        self.ps_79_a_l.setFrameShape(QFrame.Box)
        self.ps_79_a_l.setText('')
        self.gridLayout_5.addWidget(self.ps_79_a_l, 7, 1, 1, 1)
        self.ps_79_b_l = QLabel(self.groupBox_5)
        self.ps_79_b_l.setMinimumSize(QSize(0, 24))
        self.ps_79_b_l.setMaximumSize(QSize(16777215, 24))
        self.ps_79_b_l.setFrameShape(QFrame.Box)
        self.ps_79_b_l.setText('')
        self.gridLayout_5.addWidget(self.ps_79_b_l, 7, 2, 1, 1)
        self.ps_79_c_l = QLabel(self.groupBox_5)
        self.ps_79_c_l.setMinimumSize(QSize(0, 24))
        self.ps_79_c_l.setMaximumSize(QSize(16777215, 24))
        self.ps_79_c_l.setFrameShape(QFrame.Box)
        self.ps_79_c_l.setText('')
        self.gridLayout_5.addWidget(self.ps_79_c_l, 7, 3, 1, 1)
        self.ps_79_d_l = QLabel(self.groupBox_5)
        self.ps_79_d_l.setMinimumSize(QSize(0, 24))
        self.ps_79_d_l.setMaximumSize(QSize(16777215, 24))
        self.ps_79_d_l.setFrameShape(QFrame.Box)
        self.ps_79_d_l.setText('')
        self.gridLayout_5.addWidget(self.ps_79_d_l, 7, 4, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.groupBox_6 = QGroupBox(self.left_eng_win)
        self.gridLayout_6 = QGridLayout(self.groupBox_6)
        self.gridLayout_6.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_6.setSpacing(4)
        self.label_tat_l = QLabel(self.groupBox_6)
        self.label_tat_l.setMinimumSize(QSize(0, 24))
        self.label_tat_l.setMaximumSize(QSize(16777215, 24))
        self.label_tat_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_6.addWidget(self.label_tat_l, 0, 0, 1, 1)
        self.label_tt1_l = QLabel(self.groupBox_6)
        self.label_tt1_l.setMinimumSize(QSize(0, 24))
        self.label_tt1_l.setMaximumSize(QSize(16777215, 24))
        self.label_tt1_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_6.addWidget(self.label_tt1_l, 0, 1, 1, 1)
        self.label_tt2_l = QLabel(self.groupBox_6)
        self.label_tt2_l.setMinimumSize(QSize(0, 24))
        self.label_tt2_l.setMaximumSize(QSize(16777215, 24))
        self.label_tt2_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_6.addWidget(self.label_tt2_l, 0, 2, 1, 1)
        self.label_tt3_l = QLabel(self.groupBox_6)
        self.label_tt3_l.setMinimumSize(QSize(0, 24))
        self.label_tt3_l.setMaximumSize(QSize(16777215, 24))
        self.label_tt3_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_6.addWidget(self.label_tt3_l, 0, 3, 1, 1)
        self.label_tt4_l = QLabel(self.groupBox_6)
        self.label_tt4_l.setMinimumSize(QSize(0, 24))
        self.label_tt4_l.setMaximumSize(QSize(16777215, 24))
        self.label_tt4_l.setAlignment(Qt.AlignCenter)
        self.gridLayout_6.addWidget(self.label_tt4_l, 0, 4, 1, 1)
        self.tat_l = QLabel(self.groupBox_6)
        self.tat_l.setMinimumSize(QSize(0, 24))
        self.tat_l.setMaximumSize(QSize(16777215, 24))
        self.tat_l.setFrameShape(QFrame.Box)
        self.tat_l.setText('')
        self.gridLayout_6.addWidget(self.tat_l, 1, 0, 1, 1)
        self.tt1_l = QLabel(self.groupBox_6)
        self.tt1_l.setMinimumSize(QSize(0, 24))
        self.tt1_l.setMaximumSize(QSize(16777215, 24))
        self.tt1_l.setFrameShape(QFrame.Box)
        self.tt1_l.setText('')
        self.gridLayout_6.addWidget(self.tt1_l, 1, 1, 1, 1)
        self.tt2_l = QLabel(self.groupBox_6)
        self.tt2_l.setMinimumSize(QSize(0, 24))
        self.tt2_l.setMaximumSize(QSize(16777215, 24))
        self.tt2_l.setFrameShape(QFrame.Box)
        self.tt2_l.setText('')
        self.gridLayout_6.addWidget(self.tt2_l, 1, 2, 1, 1)
        self.tt3_l = QLabel(self.groupBox_6)
        self.tt3_l.setMinimumSize(QSize(0, 24))
        self.tt3_l.setMaximumSize(QSize(16777215, 24))
        self.tt3_l.setFrameShape(QFrame.Box)
        self.tt3_l.setText('')
        self.gridLayout_6.addWidget(self.tt3_l, 1, 3, 1, 1)
        self.tt4_l = QLabel(self.groupBox_6)
        self.tt4_l.setMinimumSize(QSize(0, 24))
        self.tt4_l.setMaximumSize(QSize(16777215, 24))
        self.tt4_l.setFrameShape(QFrame.Box)
        self.tt4_l.setText('')
        self.gridLayout_6.addWidget(self.tt4_l, 1, 4, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        # 调整左引擎下半部分左右两边的宽度比
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.stack_window.addWidget(self.left_eng_win)

        self.right_eng_win = QWidget(self.stack_window, flags=Qt.Widget)
        self.verticalLayout_3 = QVBoxLayout(self.right_eng_win)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(4)
        self.aux_graphics_right_eng = GraphicsView(self.right_eng_win)
        self.verticalLayout_3.addWidget(self.aux_graphics_right_eng)
        self.horizontalLayout = QHBoxLayout()
        self.verticalLayout = QVBoxLayout()
        self.main_graphics_right_eng = GraphicsView(self.right_eng_win)
        self.verticalLayout.addWidget(self.main_graphics_right_eng)
        self.groupBox = QGroupBox(self.right_eng_win)
        self.gridLayout_3 = QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(4)
        self.tf_dnst_l_r = QLabel(self.groupBox)
        self.tf_dnst_l_r.setMinimumSize(QSize(0, 24))
        self.tf_dnst_l_r.setMaximumSize(QSize(16777215, 24))
        self.tf_dnst_l_r.setFrameShape(QFrame.Box)
        self.tf_dnst_l_r.setText('')
        self.gridLayout_3.addWidget(self.tf_dnst_l_r, 1, 6, 1, 1)
        self.label_qf_upst_r = QLabel(self.groupBox)
        self.label_qf_upst_r.setMinimumSize(QSize(0, 24))
        self.label_qf_upst_r.setMaximumSize(QSize(16777215, 24))
        self.label_qf_upst_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_3.addWidget(self.label_qf_upst_r, 0, 1, 1, 1)
        self.label_tf_upst_r = QLabel(self.groupBox)
        self.label_tf_upst_r.setMinimumSize(QSize(0, 24))
        self.label_tf_upst_r.setMaximumSize(QSize(16777215, 24))
        self.label_tf_upst_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_3.addWidget(self.label_tf_upst_r, 0, 5, 1, 1)
        self.qf_dnst_l_r = QLabel(self.groupBox)
        self.qf_dnst_l_r.setMinimumSize(QSize(0, 24))
        self.qf_dnst_l_r.setMaximumSize(QSize(16777215, 24))
        self.qf_dnst_l_r.setFrameShape(QFrame.Box)
        self.qf_dnst_l_r.setText('')
        self.gridLayout_3.addWidget(self.qf_dnst_l_r, 1, 2, 1, 1)
        self.label_pf_upst_r = QLabel(self.groupBox)
        self.label_pf_upst_r.setMinimumSize(QSize(0, 24))
        self.label_pf_upst_r.setMaximumSize(QSize(16777215, 24))
        self.label_pf_upst_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_3.addWidget(self.label_pf_upst_r, 0, 3, 1, 1)
        self.label_pf_dnst_r = QLabel(self.groupBox)
        self.label_pf_dnst_r.setMinimumSize(QSize(0, 24))
        self.label_pf_dnst_r.setMaximumSize(QSize(16777215, 24))
        self.label_pf_dnst_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_3.addWidget(self.label_pf_dnst_r, 0, 4, 1, 1)
        self.qf_upst_l_r = QLabel(self.groupBox)
        self.qf_upst_l_r.setMinimumSize(QSize(0, 24))
        self.qf_upst_l_r.setMaximumSize(QSize(16777215, 24))
        self.qf_upst_l_r.setFrameShape(QFrame.Box)
        self.qf_upst_l_r.setText('')
        self.gridLayout_3.addWidget(self.qf_upst_l_r, 1, 1, 1, 1)
        self.label_l_r = QLabel(self.groupBox)
        self.label_l_r.setMinimumSize(QSize(24, 24))
        self.label_l_r.setMaximumSize(QSize(24, 24))
        self.label_l_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_3.addWidget(self.label_l_r, 1, 0, 1, 1)
        self.pf_upst_l_r = QLabel(self.groupBox)
        self.pf_upst_l_r.setMinimumSize(QSize(0, 24))
        self.pf_upst_l_r.setMaximumSize(QSize(16777215, 24))
        self.pf_upst_l_r.setFrameShape(QFrame.Box)
        self.pf_upst_l_r.setText('')
        self.gridLayout_3.addWidget(self.pf_upst_l_r, 1, 3, 1, 1)
        self.label_qf_dnst_r = QLabel(self.groupBox)
        self.label_qf_dnst_r.setMinimumSize(QSize(0, 24))
        self.label_qf_dnst_r.setMaximumSize(QSize(16777215, 24))
        self.label_qf_dnst_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_3.addWidget(self.label_qf_dnst_r, 0, 2, 1, 1)
        self.label_tf_dnst_r = QLabel(self.groupBox)
        self.label_tf_dnst_r.setMinimumSize(QSize(0, 24))
        self.label_tf_dnst_r.setMaximumSize(QSize(16777215, 24))
        self.label_tf_dnst_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_3.addWidget(self.label_tf_dnst_r, 0, 6, 1, 1)
        self.pf_dnst_l_r = QLabel(self.groupBox)
        self.pf_dnst_l_r.setMinimumSize(QSize(0, 24))
        self.pf_dnst_l_r.setMaximumSize(QSize(16777215, 24))
        self.pf_dnst_l_r.setFrameShape(QFrame.Box)
        self.pf_dnst_l_r.setText('')
        self.gridLayout_3.addWidget(self.pf_dnst_l_r, 1, 4, 1, 1)
        self.label_r_spacer = QLabel(self.groupBox)
        self.label_r_spacer.setMinimumSize(QSize(24, 24))
        self.label_r_spacer.setMaximumSize(QSize(24, 24))
        self.label_r_spacer.setText('')
        self.gridLayout_3.addWidget(self.label_r_spacer, 0, 0, 1, 1)
        self.tf_upst_l_r = QLabel(self.groupBox)
        self.tf_upst_l_r.setMinimumSize(QSize(0, 24))
        self.tf_upst_l_r.setMaximumSize(QSize(16777215, 24))
        self.tf_upst_l_r.setFrameShape(QFrame.Box)
        self.tf_upst_l_r.setText('')
        self.gridLayout_3.addWidget(self.tf_upst_l_r, 1, 5, 1, 1)
        self.pf_upst_r_r = QLabel(self.groupBox)
        self.pf_upst_r_r.setMinimumSize(QSize(0, 24))
        self.pf_upst_r_r.setMaximumSize(QSize(16777215, 24))
        self.pf_upst_r_r.setFrameShape(QFrame.Box)
        self.pf_upst_r_r.setText('')
        self.gridLayout_3.addWidget(self.pf_upst_r_r, 2, 3, 1, 1)
        self.qf_dnst_r_r = QLabel(self.groupBox)
        self.qf_dnst_r_r.setMinimumSize(QSize(0, 24))
        self.qf_dnst_r_r.setMaximumSize(QSize(16777215, 24))
        self.qf_dnst_r_r.setFrameShape(QFrame.Box)
        self.qf_dnst_r_r.setText('')
        self.gridLayout_3.addWidget(self.qf_dnst_r_r, 2, 2, 1, 1)
        self.tf_upst_r_r = QLabel(self.groupBox)
        self.tf_upst_r_r.setMinimumSize(QSize(0, 24))
        self.tf_upst_r_r.setMaximumSize(QSize(16777215, 24))
        self.tf_upst_r_r.setFrameShape(QFrame.Box)
        self.tf_upst_r_r.setText('')
        self.gridLayout_3.addWidget(self.tf_upst_r_r, 2, 5, 1, 1)
        self.pf_dnst_r_r = QLabel(self.groupBox)
        self.pf_dnst_r_r.setMinimumSize(QSize(0, 24))
        self.pf_dnst_r_r.setMaximumSize(QSize(16777215, 24))
        self.pf_dnst_r_r.setFrameShape(QFrame.Box)
        self.pf_dnst_r_r.setText('')
        self.gridLayout_3.addWidget(self.pf_dnst_r_r, 2, 4, 1, 1)
        self.label_r_r = QLabel(self.groupBox)
        self.label_r_r.setMinimumSize(QSize(24, 24))
        self.label_r_r.setMaximumSize(QSize(24, 24))
        self.label_r_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_3.addWidget(self.label_r_r, 2, 0, 1, 1)
        self.qf_upst_r_r = QLabel(self.groupBox)
        self.qf_upst_r_r.setMinimumSize(QSize(0, 24))
        self.qf_upst_r_r.setMaximumSize(QSize(16777215, 24))
        self.qf_upst_r_r.setFrameShape(QFrame.Box)
        self.qf_upst_r_r.setText('')
        self.gridLayout_3.addWidget(self.qf_upst_r_r, 2, 1, 1, 1)
        self.tf_dnst_r_r = QLabel(self.groupBox)
        self.tf_dnst_r_r.setMinimumSize(QSize(0, 24))
        self.tf_dnst_r_r.setMaximumSize(QSize(16777215, 24))
        self.tf_dnst_r_r.setFrameShape(QFrame.Box)
        self.tf_dnst_r_r.setText('')
        self.gridLayout_3.addWidget(self.tf_dnst_r_r, 2, 6, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QVBoxLayout()
        self.groupBox_3 = QGroupBox(self.right_eng_win)
        self.gridLayout = QGridLayout(self.groupBox_3)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setSpacing(4)
        self.label_a_r = QLabel(self.groupBox_3)
        self.label_a_r.setMinimumSize(QSize(0, 24))
        self.label_a_r.setMaximumSize(QSize(16777215, 24))
        self.label_a_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_a_r, 0, 1, 1, 1)
        self.label_b_r = QLabel(self.groupBox_3)
        self.label_b_r.setMinimumSize(QSize(0, 24))
        self.label_b_r.setMaximumSize(QSize(16777215, 24))
        self.label_b_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_b_r, 0, 2, 1, 1)
        self.label_c_r = QLabel(self.groupBox_3)
        self.label_c_r.setMinimumSize(QSize(0, 24))
        self.label_c_r.setMaximumSize(QSize(16777215, 24))
        self.label_c_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_c_r, 0, 3, 1, 1)
        self.label_d_r = QLabel(self.groupBox_3)
        self.label_d_r.setMinimumSize(QSize(0, 24))
        self.label_d_r.setMaximumSize(QSize(16777215, 24))
        self.label_d_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_d_r, 0, 4, 1, 1)
        self.label_e_r = QLabel(self.groupBox_3)
        self.label_e_r.setMinimumSize(QSize(0, 24))
        self.label_e_r.setMaximumSize(QSize(16777215, 24))
        self.label_e_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_e_r, 0, 5, 1, 1)
        self.label_f_r = QLabel(self.groupBox_3)
        self.label_f_r.setMinimumSize(QSize(0, 24))
        self.label_f_r.setMaximumSize(QSize(16777215, 24))
        self.label_f_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_f_r, 0, 6, 1, 1)
        self.label_pt_25_r = QLabel(self.groupBox_3)
        self.label_pt_25_r.setMinimumSize(QSize(0, 24))
        self.label_pt_25_r.setMaximumSize(QSize(16777215, 24))
        self.label_pt_25_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_pt_25_r, 1, 0, 1, 1)
        self.pt_25_a_r = QLabel(self.groupBox_3)
        self.pt_25_a_r.setMinimumSize(QSize(0, 24))
        self.pt_25_a_r.setMaximumSize(QSize(16777215, 24))
        self.pt_25_a_r.setFrameShape(QFrame.Box)
        self.pt_25_a_r.setText('')
        self.gridLayout.addWidget(self.pt_25_a_r, 1, 1, 1, 1)
        self.pt_25_b_r = QLabel(self.groupBox_3)
        self.pt_25_b_r.setMinimumSize(QSize(0, 24))
        self.pt_25_b_r.setMaximumSize(QSize(16777215, 24))
        self.pt_25_b_r.setFrameShape(QFrame.Box)
        self.pt_25_b_r.setText('')
        self.gridLayout.addWidget(self.pt_25_b_r, 1, 2, 1, 1)
        self.pt_25_c_r = QLabel(self.groupBox_3)
        self.pt_25_c_r.setMinimumSize(QSize(0, 24))
        self.pt_25_c_r.setMaximumSize(QSize(16777215, 24))
        self.pt_25_c_r.setFrameShape(QFrame.Box)
        self.pt_25_c_r.setText('')
        self.gridLayout.addWidget(self.pt_25_c_r, 1, 3, 1, 1)
        self.pt_25_d_r = QLabel(self.groupBox_3)
        self.pt_25_d_r.setMinimumSize(QSize(0, 24))
        self.pt_25_d_r.setMaximumSize(QSize(16777215, 24))
        self.pt_25_d_r.setFrameShape(QFrame.Box)
        self.pt_25_d_r.setText('')
        self.gridLayout.addWidget(self.pt_25_d_r, 1, 4, 1, 1)
        self.pt_25_e_r = QLabel(self.groupBox_3)
        self.pt_25_e_r.setMinimumSize(QSize(0, 24))
        self.pt_25_e_r.setMaximumSize(QSize(16777215, 24))
        self.pt_25_e_r.setFrameShape(QFrame.Box)
        self.pt_25_e_r.setText('')
        self.gridLayout.addWidget(self.pt_25_e_r, 1, 5, 1, 1)
        self.pt_25_f_r = QLabel(self.groupBox_3)
        self.pt_25_f_r.setMinimumSize(QSize(0, 24))
        self.pt_25_f_r.setMaximumSize(QSize(16777215, 24))
        self.pt_25_f_r.setFrameShape(QFrame.Box)
        self.pt_25_f_r.setText('')
        self.gridLayout.addWidget(self.pt_25_f_r, 1, 6, 1, 1)
        self.label_pt_31_r = QLabel(self.groupBox_3)
        self.label_pt_31_r.setMinimumSize(QSize(0, 24))
        self.label_pt_31_r.setMaximumSize(QSize(16777215, 24))
        self.label_pt_31_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_pt_31_r, 2, 0, 1, 1)
        self.pt_31_a_r = QLabel(self.groupBox_3)
        self.pt_31_a_r.setMinimumSize(QSize(0, 24))
        self.pt_31_a_r.setMaximumSize(QSize(16777215, 24))
        self.pt_31_a_r.setFrameShape(QFrame.Box)
        self.pt_31_a_r.setText('')
        self.gridLayout.addWidget(self.pt_31_a_r, 2, 1, 1, 1)
        self.pt_31_b_r = QLabel(self.groupBox_3)
        self.pt_31_b_r.setMinimumSize(QSize(0, 24))
        self.pt_31_b_r.setMaximumSize(QSize(16777215, 24))
        self.pt_31_b_r.setFrameShape(QFrame.Box)
        self.pt_31_b_r.setText('')
        self.gridLayout.addWidget(self.pt_31_b_r, 2, 2, 1, 1)
        self.pt_31_c_r = QLabel(self.groupBox_3)
        self.pt_31_c_r.setMinimumSize(QSize(0, 24))
        self.pt_31_c_r.setMaximumSize(QSize(16777215, 24))
        self.pt_31_c_r.setFrameShape(QFrame.Box)
        self.pt_31_c_r.setText('')
        self.gridLayout.addWidget(self.pt_31_c_r, 2, 3, 1, 1)
        self.pt_31_d_r = QLabel(self.groupBox_3)
        self.pt_31_d_r.setMinimumSize(QSize(0, 24))
        self.pt_31_d_r.setMaximumSize(QSize(16777215, 24))
        self.pt_31_d_r.setFrameShape(QFrame.Box)
        self.pt_31_d_r.setText('')
        self.gridLayout.addWidget(self.pt_31_d_r, 2, 4, 1, 1)
        self.pt_31_e_r = QLabel(self.groupBox_3)
        self.pt_31_e_r.setMinimumSize(QSize(0, 24))
        self.pt_31_e_r.setMaximumSize(QSize(16777215, 24))
        self.pt_31_e_r.setFrameShape(QFrame.Box)
        self.pt_31_e_r.setText('')
        self.gridLayout.addWidget(self.pt_31_e_r, 2, 5, 1, 1)
        self.label_tt_25_r = QLabel(self.groupBox_3)
        self.label_tt_25_r.setMinimumSize(QSize(0, 24))
        self.label_tt_25_r.setMaximumSize(QSize(16777215, 24))
        self.label_tt_25_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_tt_25_r, 3, 0, 1, 1)
        self.tt_25_a_r = QLabel(self.groupBox_3)
        self.tt_25_a_r.setMinimumSize(QSize(0, 24))
        self.tt_25_a_r.setMaximumSize(QSize(16777215, 24))
        self.tt_25_a_r.setFrameShape(QFrame.Box)
        self.tt_25_a_r.setText('')
        self.gridLayout.addWidget(self.tt_25_a_r, 3, 1, 1, 1)
        self.tt_25_b_r = QLabel(self.groupBox_3)
        self.tt_25_b_r.setMinimumSize(QSize(0, 24))
        self.tt_25_b_r.setMaximumSize(QSize(16777215, 24))
        self.tt_25_b_r.setFrameShape(QFrame.Box)
        self.tt_25_b_r.setText('')
        self.gridLayout.addWidget(self.tt_25_b_r, 3, 2, 1, 1)
        self.tt_25_c_r = QLabel(self.groupBox_3)
        self.tt_25_c_r.setMinimumSize(QSize(0, 24))
        self.tt_25_c_r.setMaximumSize(QSize(16777215, 24))
        self.tt_25_c_r.setFrameShape(QFrame.Box)
        self.tt_25_c_r.setText('')
        self.gridLayout.addWidget(self.tt_25_c_r, 3, 3, 1, 1)
        self.tt_25_d_r = QLabel(self.groupBox_3)
        self.tt_25_d_r.setMinimumSize(QSize(0, 24))
        self.tt_25_d_r.setMaximumSize(QSize(16777215, 24))
        self.tt_25_d_r.setFrameShape(QFrame.Box)
        self.tt_25_d_r.setText('')
        self.gridLayout.addWidget(self.tt_25_d_r, 3, 4, 1, 1)
        self.tt_25_e_r = QLabel(self.groupBox_3)
        self.tt_25_e_r.setMinimumSize(QSize(0, 24))
        self.tt_25_e_r.setMaximumSize(QSize(16777215, 24))
        self.tt_25_e_r.setFrameShape(QFrame.Box)
        self.tt_25_e_r.setText('')
        self.gridLayout.addWidget(self.tt_25_e_r, 3, 5, 1, 1)
        self.tt_25_f_r = QLabel(self.groupBox_3)
        self.tt_25_f_r.setMinimumSize(QSize(0, 24))
        self.tt_25_f_r.setMaximumSize(QSize(16777215, 24))
        self.tt_25_f_r.setFrameShape(QFrame.Box)
        self.tt_25_f_r.setText('')
        self.gridLayout.addWidget(self.tt_25_f_r, 3, 6, 1, 1)
        self.label_tt_31_r = QLabel(self.groupBox_3)
        self.label_tt_31_r.setMinimumSize(QSize(0, 24))
        self.label_tt_31_r.setMaximumSize(QSize(16777215, 24))
        self.label_tt_31_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_tt_31_r, 4, 0, 1, 1)
        self.tt_31_a_r = QLabel(self.groupBox_3)
        self.tt_31_a_r.setMinimumSize(QSize(0, 24))
        self.tt_31_a_r.setMaximumSize(QSize(16777215, 24))
        self.tt_31_a_r.setFrameShape(QFrame.Box)
        self.tt_31_a_r.setText('')
        self.gridLayout.addWidget(self.tt_31_a_r, 4, 1, 1, 1)
        self.tt_31_b_r = QLabel(self.groupBox_3)
        self.tt_31_b_r.setMinimumSize(QSize(0, 24))
        self.tt_31_b_r.setMaximumSize(QSize(16777215, 24))
        self.tt_31_b_r.setFrameShape(QFrame.Box)
        self.tt_31_b_r.setText('')
        self.gridLayout.addWidget(self.tt_31_b_r, 4, 2, 1, 1)
        self.tt_31_c_r = QLabel(self.groupBox_3)
        self.tt_31_c_r.setMinimumSize(QSize(0, 24))
        self.tt_31_c_r.setMaximumSize(QSize(16777215, 24))
        self.tt_31_c_r.setFrameShape(QFrame.Box)
        self.tt_31_c_r.setText('')
        self.gridLayout.addWidget(self.tt_31_c_r, 4, 3, 1, 1)
        self.tt_31_d_r = QLabel(self.groupBox_3)
        self.tt_31_d_r.setMinimumSize(QSize(0, 24))
        self.tt_31_d_r.setMaximumSize(QSize(16777215, 24))
        self.tt_31_d_r.setFrameShape(QFrame.Box)
        self.tt_31_d_r.setText('')
        self.gridLayout.addWidget(self.tt_31_d_r, 4, 4, 1, 1)
        self.tt_31_e_r = QLabel(self.groupBox_3)
        self.tt_31_e_r.setMinimumSize(QSize(0, 24))
        self.tt_31_e_r.setMaximumSize(QSize(16777215, 24))
        self.tt_31_e_r.setFrameShape(QFrame.Box)
        self.tt_31_e_r.setText('')
        self.gridLayout.addWidget(self.tt_31_e_r, 4, 5, 1, 1)
        self.label_pt_79_r = QLabel(self.groupBox_3)
        self.label_pt_79_r.setMinimumSize(QSize(0, 24))
        self.label_pt_79_r.setMaximumSize(QSize(16777215, 24))
        self.label_pt_79_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_pt_79_r, 5, 0, 1, 1)
        self.pt_79_a_r = QLabel(self.groupBox_3)
        self.pt_79_a_r.setMinimumSize(QSize(0, 24))
        self.pt_79_a_r.setMaximumSize(QSize(16777215, 24))
        self.pt_79_a_r.setFrameShape(QFrame.Box)
        self.pt_79_a_r.setText('')
        self.gridLayout.addWidget(self.pt_79_a_r, 5, 1, 1, 1)
        self.pt_79_b_r = QLabel(self.groupBox_3)
        self.pt_79_b_r.setMinimumSize(QSize(0, 24))
        self.pt_79_b_r.setMaximumSize(QSize(16777215, 24))
        self.pt_79_b_r.setFrameShape(QFrame.Box)
        self.pt_79_b_r.setText('')
        self.gridLayout.addWidget(self.pt_79_b_r, 5, 2, 1, 1)
        self.pt_79_c_r = QLabel(self.groupBox_3)
        self.pt_79_c_r.setMinimumSize(QSize(0, 24))
        self.pt_79_c_r.setMaximumSize(QSize(16777215, 24))
        self.pt_79_c_r.setFrameShape(QFrame.Box)
        self.pt_79_c_r.setText('')
        self.gridLayout.addWidget(self.pt_79_c_r, 5, 3, 1, 1)
        self.pt_79_d_r = QLabel(self.groupBox_3)
        self.pt_79_d_r.setMinimumSize(QSize(0, 24))
        self.pt_79_d_r.setMaximumSize(QSize(16777215, 24))
        self.pt_79_d_r.setFrameShape(QFrame.Box)
        self.pt_79_d_r.setText('')
        self.gridLayout.addWidget(self.pt_79_d_r, 5, 4, 1, 1)
        self.label_tt_79_r = QLabel(self.groupBox_3)
        self.label_tt_79_r.setMinimumSize(QSize(0, 24))
        self.label_tt_79_r.setMaximumSize(QSize(16777215, 24))
        self.label_tt_79_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_tt_79_r, 6, 0, 1, 1)
        self.tt_79_a_r = QLabel(self.groupBox_3)
        self.tt_79_a_r.setMinimumSize(QSize(0, 24))
        self.tt_79_a_r.setMaximumSize(QSize(16777215, 24))
        self.tt_79_a_r.setFrameShape(QFrame.Box)
        self.tt_79_a_r.setText('')
        self.gridLayout.addWidget(self.tt_79_a_r, 6, 1, 1, 1)
        self.tt_79_b_r = QLabel(self.groupBox_3)
        self.tt_79_b_r.setMinimumSize(QSize(0, 24))
        self.tt_79_b_r.setMaximumSize(QSize(16777215, 24))
        self.tt_79_b_r.setFrameShape(QFrame.Box)
        self.tt_79_b_r.setText('')
        self.gridLayout.addWidget(self.tt_79_b_r, 6, 2, 1, 1)
        self.tt_79_c_r = QLabel(self.groupBox_3)
        self.tt_79_c_r.setMinimumSize(QSize(0, 24))
        self.tt_79_c_r.setMaximumSize(QSize(16777215, 24))
        self.tt_79_c_r.setFrameShape(QFrame.Box)
        self.tt_79_c_r.setText('')
        self.gridLayout.addWidget(self.tt_79_c_r, 6, 3, 1, 1)
        self.tt_79_d_r = QLabel(self.groupBox_3)
        self.tt_79_d_r.setMinimumSize(QSize(0, 24))
        self.tt_79_d_r.setMaximumSize(QSize(16777215, 24))
        self.tt_79_d_r.setFrameShape(QFrame.Box)
        self.tt_79_d_r.setText('')
        self.gridLayout.addWidget(self.tt_79_d_r, 6, 4, 1, 1)
        self.label_ps_79_r = QLabel(self.groupBox_3)
        self.label_ps_79_r.setMinimumSize(QSize(0, 24))
        self.label_ps_79_r.setMaximumSize(QSize(16777215, 24))
        self.label_ps_79_r.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_ps_79_r, 7, 0, 1, 1)
        self.ps_79_a_r = QLabel(self.groupBox_3)
        self.ps_79_a_r.setMinimumSize(QSize(0, 24))
        self.ps_79_a_r.setMaximumSize(QSize(16777215, 24))
        self.ps_79_a_r.setFrameShape(QFrame.Box)
        self.ps_79_a_r.setText('')
        self.gridLayout.addWidget(self.ps_79_a_r, 7, 1, 1, 1)
        self.ps_79_b_r = QLabel(self.groupBox_3)
        self.ps_79_b_r.setMinimumSize(QSize(0, 24))
        self.ps_79_b_r.setMaximumSize(QSize(16777215, 24))
        self.ps_79_b_r.setFrameShape(QFrame.Box)
        self.ps_79_b_r.setText('')
        self.gridLayout.addWidget(self.ps_79_b_r, 7, 2, 1, 1)
        self.ps_79_c_r = QLabel(self.groupBox_3)
        self.ps_79_c_r.setMinimumSize(QSize(0, 24))
        self.ps_79_c_r.setMaximumSize(QSize(16777215, 24))
        self.ps_79_c_r.setFrameShape(QFrame.Box)
        self.ps_79_c_r.setText('')
        self.gridLayout.addWidget(self.ps_79_c_r, 7, 3, 1, 1)
        self.ps_79_d_r = QLabel(self.groupBox_3)
        self.ps_79_d_r.setMinimumSize(QSize(0, 24))
        self.ps_79_d_r.setMaximumSize(QSize(16777215, 24))
        self.ps_79_d_r.setFrameShape(QFrame.Box)
        self.ps_79_d_r.setText('')
        self.gridLayout.addWidget(self.ps_79_d_r, 7, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QGroupBox(self.right_eng_win)
        self.gridLayout_2 = QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_2.setSpacing(4)
        self.label_tat_r = QLabel(self.groupBox_2)
        self.label_tat_r.setMinimumSize(QSize(0, 24))
        self.label_tat_r.setMaximumSize(QSize(16777215, 24))
        self.label_tat_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.label_tat_r, 0, 0, 1, 1)
        self.label_tt1_r = QLabel(self.groupBox_2)
        self.label_tt1_r.setMinimumSize(QSize(0, 24))
        self.label_tt1_r.setMaximumSize(QSize(16777215, 24))
        self.label_tt1_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.label_tt1_r, 0, 1, 1, 1)
        self.label_tt2_r = QLabel(self.groupBox_2)
        self.label_tt2_r.setMinimumSize(QSize(0, 24))
        self.label_tt2_r.setMaximumSize(QSize(16777215, 24))
        self.label_tt2_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.label_tt2_r, 0, 2, 1, 1)
        self.label_tt3_r = QLabel(self.groupBox_2)
        self.label_tt3_r.setMinimumSize(QSize(0, 24))
        self.label_tt3_r.setMaximumSize(QSize(16777215, 24))
        self.label_tt3_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.label_tt3_r, 0, 3, 1, 1)
        self.label_tt4_r = QLabel(self.groupBox_2)
        self.label_tt4_r.setMinimumSize(QSize(0, 24))
        self.label_tt4_r.setMaximumSize(QSize(16777215, 24))
        self.label_tt4_r.setAlignment(Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.label_tt4_r, 0, 4, 1, 1)
        self.tat_r = QLabel(self.groupBox_2)
        self.tat_r.setMinimumSize(QSize(0, 24))
        self.tat_r.setMaximumSize(QSize(16777215, 24))
        self.tat_r.setFrameShape(QFrame.Box)
        self.tat_r.setText('')
        self.gridLayout_2.addWidget(self.tat_r, 1, 0, 1, 1)
        self.tt1_r = QLabel(self.groupBox_2)
        self.tt1_r.setMinimumSize(QSize(0, 24))
        self.tt1_r.setMaximumSize(QSize(16777215, 24))
        self.tt1_r.setFrameShape(QFrame.Box)
        self.tt1_r.setText('')
        self.gridLayout_2.addWidget(self.tt1_r, 1, 1, 1, 1)
        self.tt2_r = QLabel(self.groupBox_2)
        self.tt2_r.setMinimumSize(QSize(0, 24))
        self.tt2_r.setMaximumSize(QSize(16777215, 24))
        self.tt2_r.setFrameShape(QFrame.Box)
        self.tt2_r.setText('')
        self.gridLayout_2.addWidget(self.tt2_r, 1, 2, 1, 1)
        self.tt3_r = QLabel(self.groupBox_2)
        self.tt3_r.setMinimumSize(QSize(0, 24))
        self.tt3_r.setMaximumSize(QSize(16777215, 24))
        self.tt3_r.setFrameShape(QFrame.Box)
        self.tt3_r.setText('')
        self.gridLayout_2.addWidget(self.tt3_r, 1, 3, 1, 1)
        self.tt4_r = QLabel(self.groupBox_2)
        self.tt4_r.setMinimumSize(QSize(0, 24))
        self.tt4_r.setMaximumSize(QSize(16777215, 24))
        self.tt4_r.setFrameShape(QFrame.Box)
        self.tt4_r.setText('')
        self.gridLayout_2.addWidget(self.tt4_r, 1, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        # 调整右引擎下半部分左右两边的宽度比
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.stack_window.addWidget(self.right_eng_win)
        self.verticalLayout_4.addWidget(self.stack_window)
        self.setCentralWidget(self.centralwidget)

        self.trans_lang()
        self.stack_window.setCurrentIndex(0)

    def trans_lang(self):
        _translate = QCoreApplication.translate
        self.setWindowTitle(_translate('IFTDMonitorView', 'IFTDMonitor'))
        self.groupBox_4.setTitle(_translate('IFTDMonitorView', 'FFMK'))
        self.label_qf_upst_l.setText(_translate('IFTDMonitorView', 'QF_UPST'))
        self.label_tf_upst_l.setText(_translate('IFTDMonitorView', 'TF_UPST'))
        self.label_pf_upst_l.setText(_translate('IFTDMonitorView', 'PF_UPST'))
        self.label_pf_dnst_l.setText(_translate('IFTDMonitorView', 'PF_DNST'))
        self.label_l_l.setText(_translate('IFTDMonitorView', 'L'))
        self.label_qf_dnst_l.setText(_translate('IFTDMonitorView', 'QF_DNST'))
        self.label_tf_dnst_l.setText(_translate('IFTDMonitorView', 'TF_DNST'))
        self.label_r_l.setText(_translate('IFTDMonitorView', 'R'))
        self.groupBox_5.setTitle(_translate('IFTDMonitorView', 'Sensor'))
        self.label_a_l.setText(_translate('IFTDMonitorView', 'A'))
        self.label_b_l.setText(_translate('IFTDMonitorView', 'B'))
        self.label_c_l.setText(_translate('IFTDMonitorView', 'C'))
        self.label_d_l.setText(_translate('IFTDMonitorView', 'D'))
        self.label_e_l.setText(_translate('IFTDMonitorView', 'E'))
        self.label_f_l.setText(_translate('IFTDMonitorView', 'F'))
        self.label_pt_25_l.setText(_translate('IFTDMonitorView', 'PT25'))
        self.label_pt_31_l.setText(_translate('IFTDMonitorView', 'PT31'))
        self.label_tt_25_l.setText(_translate('IFTDMonitorView', 'TT25'))
        self.label_tt_31_l.setText(_translate('IFTDMonitorView', 'TT31'))
        self.label_pt_79_l.setText(_translate('IFTDMonitorView', 'PT79'))
        self.label_tt_79_l.setText(_translate('IFTDMonitorView', 'TT79'))
        self.label_ps_79_l.setText(_translate('IFTDMonitorView', 'PS79'))
        self.groupBox_6.setTitle(_translate('IFTDMonitorView', 'Temperatrue'))
        self.label_tat_l.setText(_translate('IFTDMonitorView', 'TAT'))
        self.label_tt1_l.setText(_translate('IFTDMonitorView', 'TT1'))
        self.label_tt2_l.setText(_translate('IFTDMonitorView', 'TT2'))
        self.label_tt3_l.setText(_translate('IFTDMonitorView', 'TT3'))
        self.label_tt4_l.setText(_translate('IFTDMonitorView', 'TT4'))
        self.groupBox.setTitle(_translate('IFTDMonitorView', 'FFMK'))
        self.label_qf_upst_r.setText(_translate('IFTDMonitorView', 'QF_UPST'))
        self.label_tf_upst_r.setText(_translate('IFTDMonitorView', 'TF_UPST'))
        self.label_pf_upst_r.setText(_translate('IFTDMonitorView', 'PF_UPST'))
        self.label_pf_dnst_r.setText(_translate('IFTDMonitorView', 'PF_DNST'))
        self.label_l_r.setText(_translate('IFTDMonitorView', 'L'))
        self.label_qf_dnst_r.setText(_translate('IFTDMonitorView', 'QF_DNST'))
        self.label_tf_dnst_r.setText(_translate('IFTDMonitorView', 'TF_DNST'))
        self.label_r_r.setText(_translate('IFTDMonitorView', 'R'))
        self.groupBox_3.setTitle(_translate('IFTDMonitorView', 'Sensor'))
        self.label_a_r.setText(_translate('IFTDMonitorView', 'A'))
        self.label_b_r.setText(_translate('IFTDMonitorView', 'B'))
        self.label_c_r.setText(_translate('IFTDMonitorView', 'C'))
        self.label_d_r.setText(_translate('IFTDMonitorView', 'D'))
        self.label_e_r.setText(_translate('IFTDMonitorView', 'E'))
        self.label_f_r.setText(_translate('IFTDMonitorView', 'F'))
        self.label_pt_25_r.setText(_translate('IFTDMonitorView', 'PT25'))
        self.label_pt_31_r.setText(_translate('IFTDMonitorView', 'PT31'))
        self.label_tt_25_r.setText(_translate('IFTDMonitorView', 'TT25'))
        self.label_tt_31_r.setText(_translate('IFTDMonitorView', 'TT31'))
        self.label_pt_79_r.setText(_translate('IFTDMonitorView', 'PT79'))
        self.label_tt_79_r.setText(_translate('IFTDMonitorView', 'TT79'))
        self.label_ps_79_r.setText(_translate('IFTDMonitorView', 'PS79'))
        self.groupBox_2.setTitle(_translate('IFTDMonitorView', 'Temperatrue'))
        self.label_tat_r.setText(_translate('IFTDMonitorView', 'TAT'))
        self.label_tt1_r.setText(_translate('IFTDMonitorView', 'TT1'))
        self.label_tt2_r.setText(_translate('IFTDMonitorView', 'TT2'))
        self.label_tt3_r.setText(_translate('IFTDMonitorView', 'TT3'))
        self.label_tt4_r.setText(_translate('IFTDMonitorView', 'TT4'))


if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    ui = IFTDMonitorView()
    ui.show()
    sys.exit(app.exec_())